# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20161027_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_changes',
        ),
    ]
