# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20160929_1337'),
        ('post', '0002_auto_20161013_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_changes',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.ManyToManyField(to='pet.Pet', verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0433\u043e'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
