# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_last_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location_longitude',
        ),
    ]
