# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=140, verbose_name='\u0418\u043c\u044f')),
                ('species', models.TextField(verbose_name='\u0412\u0438\u0434')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pet_avatars', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='\u0425\u043e\u0437\u044f\u0438\u043d')),
            ],
            options={
                'ordering': ('-name',),
                'verbose_name': '\u041f\u0438\u0442\u043e\u043c\u0435\u0446',
                'verbose_name_plural': '\u041f\u0438\u0442\u043e\u043c\u0446\u044b',
            },
        ),
    ]
