# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=140, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.TextField(verbose_name='\u0412\u0438\u0434'),
        ),
    ]
