# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_replied', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0434\u043e\u0431\u0440\u0435\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repliers', to=settings.AUTH_USER_MODEL, verbose_name='\u041e\u0442\u0432\u0435\u0447\u0430\u044e\u0449\u0438\u0439 \u043d\u0430 \u0437\u0430\u044f\u0432\u043a\u0443')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesters', to=settings.AUTH_USER_MODEL, verbose_name='\u0418\u043d\u0438\u0446\u0438\u0430\u0442\u043e\u0440 \u0437\u0430\u044f\u0432\u043a\u0438')),
            ],
        ),
    ]
